// src/components/CodeBlock.svelte
<script>
  let { text } = $props();

  let copied = $state(false);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(text);
    copied = true;
    setTimeout(() => (copied = false), 2000);
  };
</script>

<div class="absolute top-2 right-2">
  <button
    class="px-3 py-1 bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors text-sm"
    onclick={copyToClipboard}
  >
    {copied ? "Copied!" : "Copy"}
  </button>
</div>

// src/components/CodeBlock.jsx
import { useState } from "preact/hooks";

const CopyButton = ({ text }) => {
  const [copied, setCopied] = useState(false);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000); // Reset copied state after 2 seconds
  };
  const buttonStyle = {
    position: "absolute",
    margin: "10px",
    right: "0",
  };

  return (
    <div className="container has-text-right" style={buttonStyle}>
      <button className="button is-primary-dark" onClick={copyToClipboard}>
        {copied ? "Copied!" : "Copy"}
      </button>
    </div>
  );
};

export default CopyButton;
